mexPath = genpath('../build/src/release/');
addpath(mexPath);

params = struct(...
    'topLevelParams', struct(...
        'decisionMaking', true, ...
        'baselinePath', "path/to/baseline", ...
        'statePath', "path/to/state", ...
        'savePath', "path/to/save" ...
    ), ...
    'dataParams', struct(...
        'maxIntegrationTime', 1.234, ...
        'sampleRate', 32e6, ...
        'RBW', 100, ...
        'trueCenterFreq', 1, ...
        'subSpectraAveragingNumber', 20 ...
    ), ...
    'filterParams', struct(...
        'cutoffFrequency', 10e3, ...
        'poleNumber', 3, ...
        'stopbandAttenuation', 15.0 ...
    )...
);

jsonencode(params, PrettyPrint=true);

ans = mexScanRunner(jsonencode(params));

ans

clear all